baseurl = "http://ianferguson.io/"
languageCode = "en-us"
title = "Ian Ferguson"
theme = "anatole"
enableRobotsTXT = true

[indexes]
   category = "categories"
   tag = "tags"

[params]
  title = "Ian Ferguson"
  description = "Software Engineer, Cat Enthusiast"
  Description = "Software Engineer, Cat Enthusiast"
  logo = "/images/portrait-2021.jpeg"
  profilePicture = "/images/portrait-2021.jpeg"
  images = ["images/portrait-2021.jpeg"]
  mainSections = ["recipes"]
  displayMode = "dark"
  disableThemeSwitcher = true # Theme switcher is enabled by default

  github = "ianferguson"
  twitter = "ianwords"
  linkedin = "ianjamesferguson"
  email = "info@ianferguson.io"
  keybase = "ianferguson"
  cv = "/resume"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/ianwords"
[[params.social]]
    title = "github"
    url = "https://github.com/ianferguson"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/ianjamesferguson"

[menu]

  [[menu.main]]
  name = "About Me"
  weight = 200
  identifier = "about"
  url = "/"

  [[menu.main]]
  name = "Experience"
  weight = 300
  identifier = "resume"
  url = "/resume/"

  [[menu.main]]
  name = "Recipes"
  weight = 400
  identifier = "recipes"
  url = "/recipes/"

  [[menu.main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"
