baseurl = "http://ianferguson.io/"
languageCode = "en-us"
title = "Ian Ferguson"
theme = "hugo-uno"

# a lot of things are duplicated, due to themes having their own
# keys for things, and me not being sure of a theme 100% yet
[params]
  description = "Software Engineer, Human Being"
  Description = "Software Engineer, Human Being"
  logo = "/images/portrait.jpg"
  github = "ianferguson"
  twitter = "ianwords"
  linkedin = "ianjamesferguson"
  email = "info@ianferguson.io"
  keybase = "ianferguson"
  cv = "/resume"
  # bitbucket = "ianferguson"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/ianwords"
[[params.social]]
    title = "github"
    url = "https://github.com/ianferguson"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/ianjamesferguson"
